# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-20 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='parent',
            field=models.IntegerField(default=0),
        ),
    ]
