# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_menuitem_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpage',
            name='contents',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
